#!/bin/bash
set -euo pipefail

# Prover.toml is generated by build_sample_tree.mjs which builds a deterministic
# depth-16 Merkle tree containing one test member at leaf index 0.

cd "$(dirname "$0")"
node build_sample_tree.mjs
echo "Prover.toml regenerated."
